# Generated by Django 3.1.2 on 2021-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('container_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
